import { execFileSync, spawn } from 'child_process';
import { existsSync, rmSync, readFileSync, openSync, closeSync, writeFileSync } from 'fs';
import path from 'path';
import type { CacheEntry } from './cache-manager.js';
import { OWNER } from './github.js';
import { assertInsideTargets, safeTargetSubdir } from './path-safety.js';
import { validateBranch, validateRepo, validateSha } from './validators.js';

export function getTargetDir(repo: string, sha: string): string {
  return safeTargetSubdir(repo, sha);
}

function installDependencies(dir: string) {
  const hasLockfile = existsSync(path.join(dir, 'package-lock.json'));
  const args = hasLockfile
    ? ['ci', '--ignore-scripts']
    : ['install', '--ignore-scripts', '--no-audit', '--no-fund'];

  // Arbitrary preview repos must not run npm lifecycle scripts on the host by default.
  execFileSync('npm', args, { cwd: dir, stdio: 'pipe', timeout: 120_000 });
}

export async function cloneAndStart(
  repo: string,
  sha: string,
  port: number,
  opts?: {
    branch?: string;
    isLatest?: boolean;
    envVars?: Record<string, string>;
    startMode?: 'vite' | 'npm-dev';
  }
): Promise<{ dir: string; pid: number; type: 'vite' | 'static' }> {
  const safeRepo = validateRepo(repo);
  const safeSha = validateSha(sha);
  if (opts?.branch) validateBranch(opts.branch);
  const dir = safeTargetSubdir(safeRepo, safeSha);

  if (!existsSync(dir)) {
    const cloneUrl = `https://github.com/${OWNER}/${safeRepo}.git`;
    if (opts?.isLatest) {
      execFileSync('git', ['clone', cloneUrl, dir], { stdio: 'pipe' });
      execFileSync('git', ['checkout', safeSha], { cwd: dir, stdio: 'pipe' });
    } else {
      execFileSync('git', ['clone', '--depth', '50', cloneUrl, dir], { stdio: 'pipe' });
      execFileSync('git', ['checkout', safeSha], { cwd: dir, stdio: 'pipe' });
    }
  }

  // Check if package.json exists — if not, this is a static repo
  if (!existsSync(path.join(dir, 'package.json'))) {
    return { dir, pid: 0, type: 'static' };
  }

  // Write .env file if env vars provided
  if (opts?.envVars && Object.keys(opts.envVars).length > 0) {
    const envContent = Object.entries(opts.envVars)
      .map(([key, value]) => `${key}=${value}`)
      .join('\n');
    writeFileSync(path.join(dir, '.env'), envContent, 'utf-8');
  }

  installDependencies(dir);

  // Check if this project actually uses Vite
  const pkgJson = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf-8'));
  const allDeps = { ...pkgJson.dependencies, ...pkgJson.devDependencies };
  if (!allDeps['vite']) {
    // Not a Vite project — treat as static
    return { dir, pid: 0, type: 'static' };
  }

  // Verify vite is actually usable (npm install can silently produce incomplete installs)
  const viteCli = path.join(dir, 'node_modules', 'vite', 'dist', 'node', 'cli.js');
  if (!existsSync(viteCli)) {
    // Nuke node_modules and retry once
    console.warn(`[runner] Vite dist missing in ${dir}, retrying install...`);
    rmSync(path.join(dir, 'node_modules'), { recursive: true, force: true });
    installDependencies(dir);
    if (!existsSync(viteCli)) {
      throw new Error(`Vite install incomplete — ${viteCli} still missing after retry`);
    }
  }

  const hmrEnabled = !!opts?.isLatest;
  const startMode = opts?.startMode || 'vite';

  // Build env vars to pass to the process
  const processEnv = {
    ...process.env,
    PORT: String(port),
    HOST: '0.0.0.0',
    BASE: `/proxy/${port}/`,
    VITE_PORT: String(port),
    VITE_HOST: '0.0.0.0',
    VITE_BASE: `/proxy/${port}/`,
    ...(opts?.envVars || {}),
  };

  // Write HMR wrapper config so Vite WebSocket connects through the proxy
  const wrapperPath = path.join(dir, '.live-edit-vite.config.ts');
  const hasExistingConfig = existsSync(path.join(dir, 'vite.config.ts')) || existsSync(path.join(dir, 'vite.config.js'));
  const wrapperContent = hasExistingConfig
    ? `// Auto-generated by Live Edit — wraps project config with HMR settings
import { defineConfig, mergeConfig } from 'vite';
import baseConfig from './vite.config';
export default mergeConfig(baseConfig, defineConfig({
  server: {
    hmr: { clientPort: 443, protocol: 'wss', path: '/proxy/${port}/' }
  }
}));
`
    : `// Auto-generated by Live Edit — HMR config for projects without vite.config
import { defineConfig } from 'vite';
export default defineConfig({
  server: {
    hmr: { clientPort: 443, protocol: 'wss', path: '/proxy/${port}/' },
    allowedHosts: true,
  }
});
`;
  writeFileSync(wrapperPath, wrapperContent);

  // Capture stdout/stderr to a log file for debugging
  const logPath = path.join(dir, '.vite-server.log');
  const logFd = openSync(logPath, 'w');

  let child;
  if (startMode === 'npm-dev') {
    // Use npm run dev
    child = spawn('npm', ['run', 'dev'], {
      cwd: dir,
      stdio: ['ignore', logFd, logFd],
      detached: true,
      env: processEnv,
    });
  } else {
    // Use npx vite with flags (default, most reliable)
    const args = ['vite', '--config', '.live-edit-vite.config.ts', '--port', String(port), '--host', '0.0.0.0', '--strictPort', '--base', `/proxy/${port}/`];
    child = spawn('npx', args, {
      cwd: dir,
      stdio: ['ignore', logFd, logFd],
      detached: true,
      env: processEnv,
    });
  }

  child.unref();
  child.on('exit', () => {
    try { closeSync(logFd); } catch {}
  });

  await new Promise(r => setTimeout(r, 3000));

  return { dir, pid: child.pid!, type: 'vite' };
}

export async function pullLatest(entry: CacheEntry, newSha: string) {
  validateRepo(entry.repo);
  validateSha(newSha);
  if (!entry.branch) return;
  const branch = validateBranch(entry.branch);
  assertInsideTargets(entry.dir);
  execFileSync('git', ['fetch', 'origin', branch], { cwd: entry.dir, stdio: 'pipe' });
  execFileSync('git', ['reset', '--hard', `origin/${branch}`], { cwd: entry.dir, stdio: 'pipe' });
  // Quick npm install in case deps changed
  try {
    installDependencies(entry.dir);
  } catch {}
}

export async function stopServer(entry: CacheEntry) {
  if (entry.pid) {
    try {
      process.kill(-entry.pid, 'SIGTERM');
    } catch {
      try { process.kill(entry.pid, 'SIGTERM'); } catch {}
    }
  }
}

export function getServerLog(dir: string): string {
  const logPath = path.join(dir, '.vite-server.log');
  try {
    return readFileSync(logPath, 'utf-8');
  } catch {
    return '';
  }
}

export async function removeFiles(dir: string) {
  try {
    assertInsideTargets(dir);
    rmSync(dir, { recursive: true, force: true });
  } catch {}
}
